import * as XLSX from 'xlsx'

/**
 * Generates an Excel template for importing structures
 * Returns a Blob that can be downloaded
 */
export const generateExcelTemplate = (): Blob => {
  // Create a new workbook
  const wb = XLSX.utils.book_new()

  // Sheet 1: Samples
  const samplesData = [
    [
      'identifier',
      'parent',
      'name',
      'external_label',
      'role',
      'equivalent',
      'coefficient',
      'density',
      'purity',
      'molarity_value',
      'molarity_unit',
      'target_amount_value',
      'target_amount_unit',
      'location',
      'description',
      'solvent',
      'smiles',
      'molfile',
    ],
    [
      'sample1',
      'reaction1',
      'Ethanol',
      'EXT-001',
      'startingMaterial',
      '1.0',
      '1.0',
      '0.789',
      '0.995',
      '1.0',
      'M',
      '100',
      'mg',
      'Lab A',
      'Starting material for esterification',
      'Water',
      'CCO',
      '',
    ],
    [
      'sample2',
      'reaction1',
      'Acetic Acid',
      'EXT-002',
      'reactant',
      '1.1',
      '1.0',
      '1.049',
      '0.99',
      '',
      'M',
      '120',
      'mg',
      'Lab A',
      'Reactant for esterification',
      '',
      'CC(=O)O',
      '',
    ],
    [
      'sample3',
      'reaction1',
      'Ethyl Acetate',
      'EXT-003',
      'product',
      '',
      '1.0',
      '0.902',
      '0.95',
      '',
      'M',
      '50',
      'mg',
      'Lab A',
      'Main product',
      '',
      'CCOC(C)=O',
      '',
    ],
    [
      'sample4',
      'reaction2',
      'Benzaldehyde',
      'EXT-004',
      'startingMaterial',
      '1.0',
      '1.0',
      '1.044',
      '0.98',
      '',
      'M',
      '200',
      'mg',
      'Lab B',
      'Starting material for reduction',
      'THF',
      'C1=CC=C(C=C1)C=O',
      '',
    ],
    [
      'sample5',
      'reaction2',
      'Benzyl Alcohol',
      'EXT-005',
      'product',
      '',
      '1.0',
      '1.045',
      '0.95',
      '',
      'M',
      '180',
      'mg',
      'Lab B',
      'Reduction product',
      '',
      'C1=CC=C(C=C1)CO',
      '',
    ],
    [
      'sample6',
      '',
      'Standalone Compound',
      'EXT-006',
      '',
      '',
      '',
      '',
      '',
      '',
      'M',
      '',
      'mg',
      'Lab C',
      'Independent sample without reaction',
      '',
      'OCC2OC(OC1(CO)OC(CO)C(O)C1O)C(O)C(O)C2O',
      '',
    ],
  ]
  const ws_samples = XLSX.utils.aoa_to_sheet(samplesData)
  XLSX.utils.book_append_sheet(wb, ws_samples, 'Samples')

  // Sheet 2: Reactions
  const reactionsData = [
    [
      'identifier',
      'parent',
      'name',
      'description',
      'status',
      'temperature',
      'duration',
      'rxno',
      'solvent',
    ],
    [
      'reaction1',
      '',
      'Esterification',
      'Synthesis of ethyl acetate',
      'Successful',
      '25..50',
      '2h',
      'RXN-001',
      'Ethanol',
    ],
    [
      'reaction2',
      '',
      'Reduction',
      'Hydrogenation reaction',
      'Planned',
      '80',
      '4h',
      'RXN-002',
      'THF',
    ],
  ]
  const ws_reactions = XLSX.utils.aoa_to_sheet(reactionsData)
  XLSX.utils.book_append_sheet(wb, ws_reactions, 'Reactions')

  // Generate Excel file
  const wbout = XLSX.write(wb, { bookType: 'xlsx', type: 'array' })
  return new Blob([wbout], { type: 'application/octet-stream' })
}
