name: 'Run CI checks'

on: [push]

env:
  PRIMARY_NODE_VERSION: 18

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install all packages
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  test:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install all packages
        run: pnpm install

      - name: Run tests
        uses: cypress-io/github-action@v5
        with:
          build: pnpm run build
          start: pnpm start
          browser: chrome
